from .logger import Logger, LogLevel

# Set up the logger and logging
logger = Logger(LogLevel.INFO)
Logger.set_logger(logger)

# Set the version accessible from within the application
__version__ = "0.8.1"

# Useful for consistency. Use string formatting to use it in whatever format.
CHROMA_GENERATED_HEADER = "This file is generated by Chroma. Be careful."
